AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  DashboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handlers/dashboard/handler.zip
      Environment:
        Variables:
          CLIENT_ID: "id"
          CLIENT_SECRET: "secret"
      Events:
        Request:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Handler: handler
      Role: !GetAtt FunctionRole.Arn
      Runtime: go1.x
      Timeout: 5
      Tracing: Active