---
AWSTemplateFormatVersion: '2010-09-09'

Outputs:
  URL:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApiProdStage}"

Resources:
  DashboardFunction:
    Properties:
      CodeUri: ./handlers/dashboard/handler.zip
      Environment:
        Variables:
          CLIENT_ID: "id"
          CLIENT_SECRET: "secret"
      Events:
        Request:
          Properties:
            Method: GET
            Path: /
          Type: Api
      Handler: handler
      Runtime: go1.x
      Timeout: 5
      Tracing: Active
    Type: AWS::Serverless::Function

Transform: AWS::Serverless-2016-10-31
